apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: httpd
  name: httpd
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: httpd:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy: {}
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: mvInuRni3VvQqwTsA8nq
    type: GitHub
  - generic:
      secret: vkauyMB2xHCt1pWg4eXQ
    type: Generic
